name: AWS CDK Pipeline
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - run: npm ci
      - run: npm run build

      - name: cdk diff
        run: npm run cdk diff --all
        id: diff
        if: github.event_name == 'pull_request'

      - name: cdk deploy
        run: npm run cdk deploy --all
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
